version: '3.8'

services:
  api:
    build: .
    container_name: go-message-scheduler
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017
      - MESSAGES_DB_NAME=messages
      - MESSAGES_COLLECTION_NAME=messages
      - PORT=3000
      - REDIS_URI=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - CONFIG_PATH=.config
      - CONFIG_ENV=dev
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - go-message-scheduler-network

  mongo:
    image: mongo:latest
    container_name: messages-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - go-message-scheduler-network
      
  redis:
    image: redis:7-alpine
    container_name: messages-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - go-message-scheduler-network

volumes:
  mongo-data:
    name: messages-mongodb-data
  redis-data:
    name: messages-redis-data

networks:
  go-message-scheduler-network:
    name: go-message-scheduler-network