// Code generated by MockGen. DO NOT EDIT.
// Source: worker_handler.go
//
// Generated by this command:
//
//	mockgen --source=worker_handler.go --destination=worker_handler_mock.go --package=main
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkerPool is a mock of WorkerPool interface.
type MockWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolMockRecorder
	isgomock struct{}
}

// MockWorkerPoolMockRecorder is the mock recorder for MockWorkerPool.
type MockWorkerPoolMockRecorder struct {
	mock *MockWorkerPool
}

// NewMockWorkerPool creates a new mock instance.
func NewMockWorkerPool(ctrl *gomock.Controller) *MockWorkerPool {
	mock := &MockWorkerPool{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPool) EXPECT() *MockWorkerPoolMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockWorkerPool) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockWorkerPoolMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockWorkerPool)(nil).GetStatus))
}

// PauseFetching mocks base method.
func (m *MockWorkerPool) PauseFetching() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PauseFetching")
}

// PauseFetching indicates an expected call of PauseFetching.
func (mr *MockWorkerPoolMockRecorder) PauseFetching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseFetching", reflect.TypeOf((*MockWorkerPool)(nil).PauseFetching))
}

// ResumeFetching mocks base method.
func (m *MockWorkerPool) ResumeFetching() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumeFetching")
}

// ResumeFetching indicates an expected call of ResumeFetching.
func (mr *MockWorkerPoolMockRecorder) ResumeFetching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeFetching", reflect.TypeOf((*MockWorkerPool)(nil).ResumeFetching))
}
