worker:
  workerJobInterval: 100ms
mongoDB:
  seed: true
webhookClient:
  timeout: 30s
  path: /a4d12c37-21b5-4470-92ad-357329f2b48c
  host: https://webhook.site
cache:
  ttl: 24h
pool:
  numWorkers: 2
  timeout: 10s
  initialJobFetch: true
rateLimiter:
  maxTokens: 2
  refillRate: 2
  refillInterval: 2m
