basePath: /
definitions:
  main.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      recipient_phone_number:
        type: string
      sent_at:
        type: string
      status:
        type: string
      webhook_response_message_id:
        type: string
    type: object
  main.WorkerPoolActionRequest:
    properties:
      action:
        description: '"start" or "pause"'
        type: string
    type: object
  main.WorkerPoolStatusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: muratgun545@gmail.com
    name: API Support
  description: API for scheduling and managing messages
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Go Message Scheduler API
  version: "1.0"
paths:
  /sent-messages:
    get:
      consumes:
      - application/json
      description: Get all successfully sent messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Message'
            type: array
        "404":
          description: No sent messages found
        "500":
          description: Internal server error
      summary: Retrieve all sent messages
      tags:
      - messages
  /worker-pool/state:
    put:
      consumes:
      - application/json
      description: Start or pause the worker pool
      parameters:
      - description: Action to perform
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/main.WorkerPoolActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.WorkerPoolStatusResponse'
        "400":
          description: Invalid action
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Updates the worker pool state
      tags:
      - worker-pool
swagger: "2.0"
